[flatten()参数详解](https://blog.csdn.net/kuan__/article/details/116987162)

1. flatten()是对多维数据的降维函数。
2. flatten(),默认缺省参数为0，也就是说flatten()和flatte(0)效果一样。
3. python里的flatten(dim)表示，从第dim个维度开始展开，将后面的维度转化为一维.也就是说，只保留dim之前的维度，其他维度的数据全都挤在dim这一维。
4. 比如一个数据的维度是($S_0$ , $S_1$ ,$S_2$......... ,$S_n$ ), flatten(m)后的数据为($S_0$ , $S_1$ ,$S_2$，...，$S_{m-2}$，$S_{m-1}$，$S_{m}$∗$S_{m+1}$∗$S_{m+2}$∗...∗$S_n$)

In [3]:
import torch
a = torch.rand(2,3,4)
print(a)

b=a.flatten()
print(b)

c=a.flatten(1)
print(c)

tensor([[[0.4000, 0.5298, 0.0011, 0.0597],
         [0.5095, 0.1793, 0.3801, 0.7847],
         [0.4083, 0.7477, 0.8638, 0.0635]],

        [[0.8924, 0.6704, 0.0806, 0.0504],
         [0.7574, 0.3987, 0.1275, 0.1325],
         [0.4923, 0.6514, 0.9092, 0.6790]]])
tensor([0.4000, 0.5298, 0.0011, 0.0597, 0.5095, 0.1793, 0.3801, 0.7847, 0.4083,
        0.7477, 0.8638, 0.0635, 0.8924, 0.6704, 0.0806, 0.0504, 0.7574, 0.3987,
        0.1275, 0.1325, 0.4923, 0.6514, 0.9092, 0.6790])
tensor([[0.4000, 0.5298, 0.0011, 0.0597, 0.5095, 0.1793, 0.3801, 0.7847, 0.4083,
         0.7477, 0.8638, 0.0635],
        [0.8924, 0.6704, 0.0806, 0.0504, 0.7574, 0.3987, 0.1275, 0.1325, 0.4923,
         0.6514, 0.9092, 0.6790]])
