In [39]:
import torch
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
random_tensor = torch.randn(4,3)
print(torch.mean(random_tensor),torch.var(random_tensor))
random_tensor=random_tensor.squeeze().cpu().numpy()
print(random_tensor)
print(random_tensor.dtype)
print(np.mean(random_tensor),np.var(random_tensor))
# sns.histplot(random_tensor, kde=True, color="blue", label='Sample Data')
print(np.max(random_tensor),np.min(random_tensor))


tensor(0.2243) tensor(0.9407)
[[ 0.16841277  0.7315615   0.04677292]
 [-1.4771177   0.47612885  0.01772557]
 [ 1.0373527  -0.17775667  1.557288  ]
 [ 0.39485455 -1.505543    1.421772  ]]
float32
0.22428763 0.86231774
1.557288 -1.505543


In [42]:
import torch
import numpy as np
random_tensor = torch.randn(4,3)
print(torch.mean(random_tensor),torch.var(random_tensor))
random_tensor=random_tensor.squeeze()
print(random_tensor)
print(torch.sum(random_tensor, dim=0, keepdim=True))


tensor(-0.0542) tensor(0.8905)
tensor([[ 0.4011, -0.3874, -1.7251],
        [ 0.7053, -1.0921,  0.1786],
        [ 0.8621,  0.9434,  1.1410],
        [-0.3642, -1.3244,  0.0118]])
tensor([[ 1.6043, -1.8606, -0.3937]])
